version: "3.7"
services:
    # imagem
    api:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./sghq_back:/var/www
        networks:
            - sghq

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8011:80
        volumes:
            - ./sghq_back:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sghq

    # mysql
    db_sghq:
        image: mysql:8.0
        restart: unless-stopped
        ports:
          - 3311:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./sghq_back/.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - sghq

networks:
    sghq:
        driver: bridge
