version: "3.7"
services:
    # imagem
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sghq

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8011:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - sghq

    # mysql
    db_sghq:
        image: mysql:8.0
        restart: unless-stopped
        ports:
          - 3311:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - sghq

networks:
    sghq:
        driver: bridge
